export const projectsData = [
  {
    id: 1,
    category: {
      pt: "Landing page institucional",
      en: "Institutional landing page",
      es: "Landing page institucional",
      de: "Institutionelle Landingpage",
      it: "Landing page istituzionale",
    },
    highlight: {
      pt: "Alta performance e comunicação visual para evento oficial.",
      en: "High performance and strong visual communication for an official event.",
      es: "Alto rendimiento y comunicación visual sólida para un evento oficial.",
      de: "Hohe Performance und starke visuelle Kommunikation fuer ein offizielles Event.",
      it: "Alta performance e comunicazione visiva forte per un evento ufficiale.",
    },
    stack: [
      { name: "React", icon: "/react.webp" },
      { name: "Vite", icon: "/vite.webp" },
      { name: "Javascript", icon: "/javascript.svg" },
      { name: "Node Js", icon: "/nodejs.svg" },
      { name: "Css", icon: "/css.webp" },
      { name: "Tailwind", icon: "/tailwind.webp" },
      { name: "Material UI", icon: "/material-ui.svg" },
      { name: "Swiper Js", icon: "/swiperjs.svg" },
      { name: "Framer Motion", icon: "/framer-motion.webp" },
      { name: "Chart Js", icon: "/chartjs.svg" },
    ],
    name: "COP 15 UFMS",
    deploy: "https://cop15.ufms.br",
    description: {
      pt: "Desenvolvimento da Landing Page oficial do evento em parceria com a Mega Júnior - UFMS. O projeto focou em entregar uma solução de alta performance e design refinado, servindo como o hub digital principal para discussões globais sobre biodiversidade.",
      en: "Development of the official event landing page in partnership with Mega Júnior - UFMS. The project focused on delivering a high-performance solution with refined design, serving as the main digital hub for global biodiversity discussions.",
      es: "Desarrollo de la landing page oficial del evento en alianza con Mega Júnior - UFMS. El proyecto se centró en entregar una solución de alto rendimiento y diseño refinado, funcionando como el principal hub digital para debates globales sobre biodiversidad.",
      de: "Entwicklung der offiziellen Event-Landingpage in Partnerschaft mit Mega Junior - UFMS. Fokus auf eine leistungsstarke Loesung mit feinem Design als zentraler digitaler Hub fuer weltweite Diskussionen zur Biodiversitaet.",
      it: "Sviluppo della landing page ufficiale dell'evento in partnership con Mega Junior - UFMS. Il progetto ha puntato su alte prestazioni e design curato, fungendo da hub digitale principale per discussioni globali sulla biodiversita.",
    },
    img: "/11.webp",
  },
  {
    id: 2,
    category: {
      pt: "Aplicação full stack",
      en: "Full stack application",
      es: "Aplicación full stack",
      de: "Full-Stack-Anwendung",
      it: "Applicazione full stack",
    },
    highlight: {
      pt: "Fluxo de compra com pagamento, autenticação e catálogo gamer.",
      en: "Purchase flow with payments, authentication and a gamer catalog.",
      es: "Flujo de compra con pagos, autenticación y catálogo gamer.",
      de: "Kaufablauf mit Zahlungen, Authentifizierung und Gamer-Katalog.",
      it: "Flusso di acquisto con pagamenti, autenticazione e catalogo gaming.",
    },
    stack: [
      { name: "React", icon: "/react.webp" },
      { name: "Vite", icon: "/vite.webp" },
      { name: "Javascript", icon: "/javascript.svg" },
      { name: "Typescript", icon: "/typescript.svg" },
      { name: "Css", icon: "/css.webp" },
      { name: "Swiper Js", icon: "/swiperjs.svg" },
      { name: "PostgreSQL", icon: "/postgresql.svg" },
      { name: "Express", icon: "/express.svg" },
      { name: "Mercado Pago", icon: "/mercado_pago.webp" },
    ],
    name: "E-Commerce gamer",
    github: "https://github.com/enzovalencuela/e-commerce-gamer",
    deploy: "https://enzovalencuela-e-commerce.vercel.app",
    img: "/4.webp",
    description: {
      pt: "E-commerce completo com fluxo de pagamento automatizado, autenticação segura e design responsivo. Focado em resolver desafios reais de integração de APIs financeiras e segurança de dados do usuário.",
      en: "Complete e-commerce with automated payment flow, secure authentication and responsive design. Focused on solving real-world challenges involving financial API integration and user data security.",
      es: "E-commerce completo con flujo de pago automatizado, autenticación segura y diseño responsivo. Enfocado en resolver desafíos reales de integración con APIs financieras y seguridad de datos del usuario.",
      de: "Vollstaendiger E-Commerce mit automatisiertem Zahlungsfluss, sicherer Authentifizierung und responsivem Design. Fokus auf reale Herausforderungen bei Finanz-API-Integration und Datenschutz.",
      it: "E-commerce completo con flusso di pagamento automatizzato, autenticazione sicura e design responsive. Focalizzato su sfide reali di integrazione con API finanziarie e sicurezza dei dati utente.",
    },
  },
  {
    id: 3,
    category: {
      pt: "Sistema de gestão",
      en: "Management system",
      es: "Sistema de gestión",
      de: "Management-System",
      it: "Sistema di gestione",
    },
    highlight: {
      pt: "Controle de oficina, clientes e inventário em um painel único.",
      en: "Workshop, customer and inventory control in a single dashboard.",
      es: "Control de taller, clientes e inventario en un solo panel.",
      de: "Steuerung von Werkstatt, Kunden und Bestand in einem einzigen Dashboard.",
      it: "Controllo di officina, clienti e inventario in un unico dashboard.",
    },
    name: "Pedal de Prata",
    description: {
      pt: "Gerenciamento para oficina de bicicletas. Possui controle de ordens de serviço, catálogo de serviços, gestão de clientes e inventário de bikes à venda. Implementa segurança rigorosa com Firebase Admin SDK e banco de dados relacional com Prisma.",
      en: "Management system for a bicycle workshop. Includes work order control, service catalog, customer management and inventory for bikes on sale. Implements strong security with Firebase Admin SDK and a relational database using Prisma.",
      es: "Sistema de gestión para taller de bicicletas. Incluye control de órdenes de servicio, catálogo de servicios, gestión de clientes e inventario de bicicletas en venta. Implementa seguridad sólida con Firebase Admin SDK y base de datos relacional con Prisma.",
      de: "Management-System fuer eine Fahrrad-Werkstatt: Arbeitsauftraege, Servicekatalog, Kundenverwaltung und Verkaufsinventar. Starke Sicherheit mit Firebase Admin SDK und relationaler Datenbank via Prisma.",
      it: "Sistema di gestione per officina di biciclette: controllo ordini di servizio, catalogo servizi, gestione clienti e inventario bici in vendita. Sicurezza avanzata con Firebase Admin SDK e database relazionale con Prisma.",
    },
    stack: [
      { name: "Next.js", icon: "/next.js.webp" },
      { name: "React", icon: "/react.webp" },
      { name: "Typescript", icon: "/typescript.svg" },
      { name: "Tailwind CSS", icon: "/tailwind.webp" },
      { name: "Prisma", icon: "/prisma.webp" },
      { name: "Firebase", icon: "/firebase.svg" },
      { name: "PostgreSQL", icon: "/postgresql.svg" },
      { name: "Three.js", icon: "/threejs.svg" },
    ],
    github: "https://github.com/enzovalencuela/Pedal-de-Prata",
    deploy: "https://pedal-de-prata.vercel.app/",
    img: "/12.webp",
  },
  {
    id: 4,
    category: {
      pt: "Produtividade web",
      en: "Web productivity",
      es: "Productividad web",
      de: "Web-Produktivitaet",
      it: "Produttivita web",
    },
    highlight: {
      pt: "Organização visual de tarefas com foco em simplicidade de uso.",
      en: "Visual task organization focused on ease of use.",
      es: "Organización visual de tareas con foco en simplicidad de uso.",
      de: "Visuelle Aufgabenorganisation mit Fokus auf einfacher Bedienung.",
      it: "Organizzazione visiva delle attivita con focus sulla semplicita d'uso.",
    },
    stack: [
      { name: "React", icon: "/react.webp" },
      { name: "Next.js", icon: "/next.js.webp" },
      { name: "Javascript", icon: "/javascript.svg" },
      { name: "Tailwind", icon: "/tailwind.webp" },
      { name: "Firebase", icon: "/firebase.svg" },
      { name: "Node Js", icon: "/nodejs.svg" },
      { name: "Express", icon: "/express.svg" },
      { name: "PostgreSQL", icon: "/postgresql.svg" },
      { name: "Dnd Kit", icon: "/dnd_kit.webp" },
    ],
    name: "Nexgen Tasks",
    github: "https://github.com/enzovalencuela/MyToDoList",
    deploy: "https://tasks.enzovalencuela.com",
    img: "/13.webp",
    description: {
      pt: "Sua Lista de Tarefas! O Nexgen Tasks é a solução perfeita para você! Desenvolvido para ser intuitivo e eficiente, ele te ajuda a gerenciar suas atividades diárias, projetos e ideias de forma simples e visual.",
      en: "Your task list! Nexgen Tasks is the perfect solution for you. Built to be intuitive and efficient, it helps you manage your daily activities, projects and ideas in a simple and visual way.",
      es: "¡Tu lista de tareas! Nexgen Tasks es la solución perfecta para ti. Desarrollado para ser intuitivo y eficiente, te ayuda a gestionar tus actividades diarias, proyectos e ideas de forma simple y visual.",
      de: "Deine Aufgabenliste! Nexgen Tasks ist die ideale Loesung: intuitiv und effizient, um taegliche Aktivitaeten, Projekte und Ideen einfach und visuell zu organisieren.",
      it: "La tua lista di attivita! Nexgen Tasks e la soluzione perfetta: intuitivo ed efficiente, ti aiuta a gestire attivita quotidiane, progetti e idee in modo semplice e visivo.",
    },
  },
  {
    id: 5,
    category: {
      pt: "Plataforma de consulta",
      en: "Search platform",
      es: "Plataforma de consulta",
      de: "Abfrageplattform",
      it: "Piattaforma di consultazione",
    },
    highlight: {
      pt: "Busca e visualização de dados sobre futebol mundial.",
      en: "Search and visualization of global football data.",
      es: "Búsqueda y visualización de datos sobre fútbol mundial.",
    },
    stack: [
      { name: "React", icon: "/react.webp" },
      { name: "Next.js", icon: "/next.js.webp" },
      { name: "Javascript", icon: "/javascript.svg" },
      { name: "Css", icon: "/css.webp" },
    ],
    name: "World Football Players",
    github: "https://github.com/enzovalencuela/World-Football-Players",
    deploy: "https://world-football-players.vercel.app",
    description: {
      pt: "O World Football Players é um site que permite visualizar informações sobre jogadores de futebol, técnicos, clubes e seleções.",
      en: "World Football Players is a website that lets users view information about football players, coaches, clubs and national teams.",
      es: "World Football Players es un sitio que permite visualizar información sobre jugadores de fútbol, entrenadores, clubes y selecciones.",
      de: "Website zur Anzeige von Daten zu Fussballspielern, Trainern, Vereinen und Nationalteams.",
      it: "Sito per consultare informazioni su calciatori, allenatori, club e nazionali.",
    },
    img: "/2.webp",
  },
  {
    id: 6,
    category: {
      pt: "Consumo de API",
      en: "API consumption",
      es: "Consumo de API",
      de: "API-Anbindung",
      it: "Consumo API",
    },
    highlight: {
      pt: "Busca de perfis públicos com integração à GitHub API.",
      en: "Search for public profiles with GitHub API integration.",
      es: "Búsqueda de perfiles públicos con integración a la API de GitHub.",
      de: "Suche nach oeffentlichen Profilen mit GitHub-API-Integration.",
      it: "Ricerca profili pubblici con integrazione alla GitHub API.",
    },
    stack: [
      { name: "React", icon: "/react.webp" },
      { name: "Vite", icon: "/vite.webp" },
      { name: "Javascript", icon: "/javascript.svg" },
      { name: "Css", icon: "/css.webp" },
    ],
    name: "Projeto Github API",
    github: "https://github.com/enzovalencuela/Projeto-Github-API",
    deploy: "https://enzovalencuela-projeto-github-api.netlify.app",
    img: "/3.webp",
    description: {
      pt: "Aplicação web construída com React que consome a GitHub API para buscar informações públicas de usuários. Basta digitar o nome de usuário do GitHub para visualizar os dados como: Nome, Bio, Foto de perfil",
      en: "Web application built with React that consumes the GitHub API to fetch public user information. Just type a GitHub username to view data such as name, bio and profile picture.",
      es: "Aplicación web construida con React que consume la API de GitHub para buscar información pública de usuarios. Solo escribe el nombre de usuario de GitHub para ver datos como nombre, biografía y foto de perfil.",
      de: "Web-App in React, die die GitHub-API nutzt, um oeffentliche Nutzerinformationen abzurufen. Gib einfach einen GitHub-Nutzernamen ein, um Name, Bio und Profilbild zu sehen.",
      it: "Applicazione web in React che usa la GitHub API per recuperare informazioni pubbliche degli utenti. Basta inserire uno username GitHub per vedere nome, bio e foto profilo.",
    },
  },
  {
    id: 7,
    category: {
      pt: "Landing page",
      en: "Landing page",
      es: "Landing page",
      de: "Landingpage",
      it: "Landing page",
    },
    highlight: {
      pt: "Página promocional com foco em apresentação e conversão visual.",
      en: "Promotional page focused on presentation and visual conversion.",
      es: "Página promocional con foco en presentación y conversión visual.",
      de: "Promoseite mit Fokus auf Darstellung und visueller Conversion.",
      it: "Pagina promozionale focalizzata su presentazione e conversione visiva.",
    },
    stack: [
      { name: "HTML", icon: "/html.webp" },
      { name: "Javascript", icon: "/javascript.svg" },
      { name: "css", icon: "/css.webp" },
      { name: "Swiper Js", icon: "/swiperjs.svg" },
    ],
    name: "Landing Page",
    github: "https://github.com/enzovalencuela/landing-page",
    deploy: "https://enzovalencuela-landing-page-dnc.netlify.app",
    img: "/10.webp",
    description: {
      pt: "Este projeto é uma landing page fictícia. A página foi desenvolvida com foco em design visual atraente e experiência do usuário, utilizando boas práticas de HTML, CSS, Javascript e Swiper Js.",
      en: "This project is a fictional landing page. It was developed with a focus on attractive visual design and user experience, using good practices in HTML, CSS, JavaScript and Swiper Js.",
      es: "Este proyecto es una landing page ficticia. La página fue desarrollada con foco en diseño visual atractivo y experiencia del usuario, utilizando buenas prácticas de HTML, CSS, JavaScript y Swiper Js.",
      de: "Fiktive Landingpage mit Fokus auf ansprechendes visuelles Design und User Experience. Erstellt mit bewaehrten Praktiken in HTML, CSS, JavaScript und Swiper Js.",
      it: "Landing page fittizia sviluppata con attenzione a design visivo e UX, utilizzando buone pratiche di HTML, CSS, JavaScript e Swiper Js.",
    },
  },
  {
    id: 8,
    category: {
      pt: "Dashboard operacional",
      en: "Operational dashboard",
      es: "Dashboard operativo",
      de: "Operatives Dashboard",
      it: "Dashboard operativa",
    },
    highlight: {
      pt: "Ferramenta de vistoria preventiva para processos internos.",
      en: "Preventive inspection tool for internal processes.",
      es: "Herramienta de inspección preventiva para procesos internos.",
      de: "Tool fuer vorbeugende Pruefungen in internen Prozessen.",
      it: "Strumento di ispezione preventiva per processi interni.",
    },
    stack: [
      { name: "React", icon: "/react.webp" },
      { name: "Next.js", icon: "/next.js.webp" },
      { name: "Javascript", icon: "/javascript.svg" },
      { name: "Tailwind", icon: "/tailwind.webp" },
      { name: "Chart Js", icon: "/chartjs.svg" },
      { name: "Mongodb", icon: "/mongodb.webp" },
    ],
    name: "Projeto Proxion",
    github: "https://github.com/enzovalencuela/Projeto-Proxion",
    deploy: "",
    img: "/5.webp",
    description: {
      pt: "Proxion é uma plataforma web desenvolvida como uma ferramenta preventiva de vistoria de equipamentos, voltada à otimização de processos internos e ao monitoramento detalhado de inspeções técnicas.",
      en: "Proxion is a web platform built as a preventive equipment inspection tool, focused on optimizing internal processes and providing detailed monitoring of technical inspections.",
      es: "Proxion es una plataforma web desarrollada como herramienta preventiva de inspección de equipos, orientada a optimizar procesos internos y al monitoreo detallado de inspecciones técnicas.",
      de: "Proxion ist eine Webplattform als Tool fuer vorbeugende Geraetepruefungen, mit Fokus auf Prozessoptimierung und detailliertes Monitoring technischer Inspektionen.",
      it: "Proxion e una piattaforma web pensata come strumento di ispezione preventiva delle attrezzature, focalizzata sull'ottimizzazione dei processi interni e sul monitoraggio dettagliato delle ispezioni tecniche.",
    },
  },
  {
    id: 9,
    category: {
      pt: "Landing page temática",
      en: "Themed landing page",
      es: "Landing page temática",
      de: "Themen-Landingpage",
      it: "Landing page a tema",
    },
    highlight: {
      pt: "Projeto React/Vite com múltiplas seções e proposta editorial.",
      en: "React/Vite project with multiple sections and an editorial proposal.",
      es: "Proyecto React/Vite con múltiples secciones y propuesta editorial.",
      de: "React/Vite-Projekt mit mehreren Abschnitten und redaktioneller Ausrichtung.",
      it: "Progetto React/Vite con piu sezioni e taglio editoriale.",
    },
    stack: [
      { name: "React", icon: "/react.webp" },
      { name: "Vite", icon: "/vite.webp" },
      { name: "Javascript", icon: "/javascript.svg" },
      { name: "Css", icon: "/css.webp" },
    ],
    name: "Blog de Arquitetura",
    github: "https://github.com/enzovalencuela/projeto-blog",
    deploy: "https://enzovalencuela-projeto-blog.netlify.app/",
    description: {
      pt: "Este projeto foi desenvolvido utilizando React e Vite. Ele simula uma página de arquitetura fictícia, funcionando como uma landing page com múltiplas seções, e demonstra a aplicação de diversos conceitos fundamentais do React.",
      en: "This project was developed using React and Vite. It simulates a fictional architecture website, working as a multi-section landing page and demonstrating several fundamental React concepts.",
      es: "Este proyecto fue desarrollado utilizando React y Vite. Simula una página ficticia de arquitectura, funcionando como una landing page con múltiples secciones y demostrando varios conceptos fundamentales de React.",
      de: "Projekt in React und Vite, das eine fiktive Architektur-Website simuliert - als Landingpage mit mehreren Sektionen und Demonstration zentraler React-Konzepte.",
      it: "Progetto sviluppato con React e Vite che simula un sito di architettura fittizio: landing page multi-sezione che dimostra concetti fondamentali di React.",
    },
    img: "/8.webp",
  },

  {
    id: 12,
    category: {
      pt: "Dashboard analítico",
      en: "Analytics dashboard",
      es: "Dashboard analítico",
      de: "Analyse-Dashboard",
      it: "Dashboard analitica",
    },
    highlight: {
      pt: "Painel de vendas com visualização de métricas e gráficos.",
      en: "Sales dashboard with metric and chart visualization.",
      es: "Panel de ventas con visualización de métricas y gráficos.",
      de: "Verkaufs-Dashboard mit Kennzahlen und Diagrammen.",
      it: "Dashboard vendite con visualizzazione di metriche e grafici.",
    },
    stack: [
      { name: "React", icon: "/react.webp" },
      { name: "Vite", icon: "/vite.webp" },
      { name: "Typescript", icon: "/typescript.svg" },
      { name: "styled-components", icon: "/styled-components.svg" },
      { name: "Material UI", icon: "/material-ui.svg" },
      { name: "Chart Js", icon: "/chartjs.svg" },
      { name: "Axios", icon: "/axios.svg" },
      { name: "Cypress", icon: "/cypress.svg" },
    ],
    name: "Dashboard de Vendas",
    github: "https://github.com/enzovalencuela/projeto-sales-dashboard",
    deploy: "https://projeto-sales-dashboard.vercel.app/",
    img: "/9.webp",
    description: {
      pt: "Sales Dashboard, para gerenciamento de vendas. Este projeto foi uma ótima oportunidade para aprofundar minhas habilidades e trabalhar com uma stack super moderna e requisitada no mercado.",
      en: "Sales dashboard for sales management. This project was a great opportunity to deepen my skills and work with a modern stack that is highly valued in the market.",
      es: "Dashboard de ventas para gestión comercial. Este proyecto fue una gran oportunidad para profundizar mis habilidades y trabajar con una stack moderna y muy valorada en el mercado.",
      de: "Sales-Dashboard fuer das Vertriebsmanagement. Eine tolle Gelegenheit, Kenntnisse zu vertiefen und mit einem modernen, am Markt gefragten Stack zu arbeiten.",
      it: "Dashboard vendite per la gestione commerciale. Ottima occasione per approfondire competenze e lavorare con uno stack moderno e richiesto dal mercato.",
    },
  },
];

export function slugifyProjectName(name) {
  return name
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export const projectsWithSlug = projectsData.map((project) => ({
  ...project,
  slug: slugifyProjectName(project.name),
}));

export function getProjectTranslation(project, language = "pt") {
  return {
    ...project,
    category: project.category?.[language] || project.category?.pt || "",
    highlight: project.highlight?.[language] || project.highlight?.pt || "",
    description:
      project.description?.[language] || project.description?.pt || "",
  };
}
