export const projectsData = [
  {
    id: 1,
    stack: [
      { name: "React", icon: "/react.png" },
      { name: "Vite", icon: "/vite.png" },
      { name: "Typescript", icon: "/typescript.svg" },
      { name: "styled-components", icon: "/styled-components.svg" },
      { name: "Material UI", icon: "/material-ui.svg" },
      { name: "Chart Js", icon: "/chartjs.svg" },
      { name: "Axios", icon: "/axios.svg" },
      { name: "Cypress", icon: "/cypress.svg" },
    ],
    name: "Dashboard de Vendas",
    github: "https://github.com/enzovalencuela/projeto-sales-dashboard",
    deploy: "https://projeto-sales-dashboard.vercel.app/",
    img: "/9.png",
    description:
      "Desenvolvi um Sales Dashboard, para gerenciamento de vendas. Este projeto foi uma ótima oportunidade para aprofundar minhas habilidades e trabalhar com uma stack super moderna e requisitada no mercado.",
  },
  {
    id: 2,
    stack: [
      { name: "React", icon: "/react.png" },
      { name: "Next.js", icon: "/next.js.png" },
      { name: "Javascript", icon: "/javascript.svg" },
      { name: "Tailwind", icon: "/tailwind.png" },
      { name: "Firebase", icon: "/firebase.svg" },
      { name: "Node Js", icon: "/nodejs.svg" },
      { name: "Express", icon: "/express.svg" },
      { name: "PostgreSQL", icon: "/postgresql.svg" },
      { name: "Dnd Kit", icon: "/dnd_kit.jpg" },
    ],
    name: "Jubitasks",
    github: "https://github.com/MEGA-JR-Grupo-3/megajr-front-end",
    deploy: "https://jubitasks.netlify.app",
    img: "/7.png",
    description:
      "Sua Lista de Tarefas! O Jubitasks é a solução perfeita para você! Desenvolvido para ser intuitivo e eficiente, ele te ajuda a gerenciar suas atividades diárias, projetos e ideias de forma simples e visual.",
  },
  {
    id: 3,
    stack: [
      { name: "HTML", icon: "/html.png" },
      { name: "Javascript", icon: "/javascript.svg" },
      { name: "css", icon: "/css.png" },
      { name: "Swiper Js", icon: "/swiperjs.svg" },
    ],
    name: "Landing Page",
    github: "https://github.com/enzovalencuela/landing-page",
    deploy: "https://enzovalencuela-landing-page-dnc.netlify.app",
    img: "/10.png",
    description:
      "Este projeto é uma landing page fictícia. A página foi desenvolvida com foco em design visual atraente e experiência do usuário, utilizando boas práticas de HTML, CSS, Javascript e Swiper Js.",
  },
  {
    id: 4,
    stack: [
      { name: "React", icon: "/react.png" },
      { name: "Vite", icon: "/vite.png" },
      { name: "Javascript", icon: "/javascript.svg" },
      { name: "Typescript", icon: "/typescript.svg" },
      { name: "Css", icon: "/css.png" },
      { name: "Swiper Js", icon: "/swiperjs.svg" },
      { name: "PostgreSQL", icon: "/postgresql.svg" },
      { name: "Express", icon: "/express.svg" },
      { name: "Mercado Pago", icon: "/mercado_pago.png" },
    ],
    name: "E-Commerce gamer",
    github: "https://github.com/enzovalencuela/e-commerce-gamer",
    deploy: "https://enzovalencuela-e-commerce.vercel.app",
    img: "/4.png",
    description:
      "Este é um projeto de um e-commerce para o público gamer. A aplicação oferece um sistema de compras, login e cadastro, permitindo aos usuários criar e gerenciar suas contas.",
  },
  {
    id: 5,
    stack: [
      { name: "React", icon: "/react.png" },
      { name: "Vite", icon: "/vite.png" },
      { name: "Javascript", icon: "/javascript.svg" },
      { name: "Css", icon: "/css.png" },
    ],
    name: "Projeto Github API",
    github: "https://github.com/enzovalencuela/Projeto-Github-API",
    deploy: "https://enzovalencuela-projeto-github-api.netlify.app",
    img: "/3.png",
    description:
      "Aplicação web construída com React que consome a GitHub API para buscar informações públicas de usuários. Basta digitar o nome de usuário do GitHub para visualizar os dados como: Nome, Bio, Foto de perfil",
  },
  {
    id: 6,
    stack: [
      { name: "React", icon: "/react.png" },
      { name: "Next.js", icon: "/next.js.png" },
      { name: "Javascript", icon: "/javascript.svg" },
      { name: "Css", icon: "/css.png" },
    ],
    name: "World Football Players",
    github: "https://github.com/enzovalencuela/World-Football-Players",
    deploy: "https://world-football-players.vercel.app",
    description:
      "O World Football Players é um site que permite visualizar informações sobre jogadores de futebol, técnicos, clubes e seleções.",
    img: "/2.png",
  },
  {
    id: 7,
    stack: [
      { name: "React", icon: "/react.png" },
      { name: "Next.js", icon: "/next.js.png" },
      { name: "Javascript", icon: "/javascript.svg" },
      { name: "Tailwind", icon: "/tailwind.png" },
      { name: "Chart Js", icon: "/chartjs.svg" },
      { name: "Mongodb", icon: "/mongodb.png" },
    ],
    name: "Projeto Proxion",
    github: "https://github.com/enzovalencuela/Projeto-Proxion",
    deploy: "",
    img: "/5.png",
    description:
      "Proxion é uma plataforma web desenvolvida como uma ferramenta preventiva de vistoria de equipamentos, voltada à otimização de processos internos e ao monitoramento detalhado de inspeções técnicas.",
  },
  {
    id: 8,
    stack: [
      { name: "React", icon: "/react.png" },
      { name: "Vite", icon: "/vite.png" },
      { name: "Javascript", icon: "/javascript.svg" },
      { name: "Css", icon: "/css.png" },
    ],
    name: "Blog de Arquitetura",
    github: "https://github.com/enzovalencuela/projeto-blog",
    deploy: "https://enzovalencuela-projeto-blog.netlify.app/",
    description:
      "Este projeto foi desenvolvido utilizando React e Vite. Ele simula uma página de arquitetura fictícia, funcionando como uma landing page com múltiplas seções, e demonstra a aplicação de diversos conceitos fundamentais do React.",
    img: "/8.png",
  },
];
